deployment:
  tasks:
    - export DEPLOYPATH=/home2/yamad427/public_html/
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R .well-known $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R baiviet $DEPLOYPATH
    - /bin/cp -R doduonghuyet $DEPLOYPATH
    - /bin/cp -R dohuyetap $DEPLOYPATH
    - /bin/cp -R hutsua $DEPLOYPATH
    - /bin/cp -R nhietke $DEPLOYPATH
    - /bin/cp -R taobaiviet $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp google10c778558150934d.html $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
